[DISCORD]

TOKEN = TODO
GUILDID = TODO

[DATABASE]
dialect = mysql             # postgresql, mysql, sqlite, etc.
driver = pymysql            # optional, e.g., psycopg, pymysql, mariadbconnector
username = myuser           # ignored for sqlite
password = myP@ssword!      # ignored for sqlite
host = localhost            # ignored for sqlite
port = 5432                 # optional, ignored for sqlite
dbname = mydatabase.sqlite  # for sqlite, can be a file path

[SETTINGS]

BOTNAME = TODO
WHITELIST_LINK = TODO
PERMISSIONS = perm1, perm2, perm3

#Format the entries like the example down below possible perms are, if you want to add additional perms use the PERMISSIONS section above:
#    "startvote",
#    "changemap",
#    "pause",
#    "cheat",
#    "private",
#    "balance",
#    "chat",
#    "kick",
#    "ban",
#    "config",
#    "cameraman",
#    "immune",
#    "manageserver",
#    "featuretest",
#    "reserve",
#    "demos",
#    "clientdemos",
#    "debug",
#    "teamchange",
#    "forceteamchange",
#    "canseeadminchat"
# Seperate perms by |

[PERMISSION_ROLES]

ADMIN = discord_role_id, kick|ban

#Each key in WHITELIST_ROLES should also have an entry in WHITELIST_NAMES and vice versa

[WHITELIST_ROLES]
#The ID's of each role
#ROLENAME = ROLEID, Nmbr-whitelists
WHITELIST =  1234, 1

[DISCORD_COMMAND_PERMISSIONS]
# Gives permission to setup the explainer embed
EXPLAIN_EMBED = 123 
# Gives permission to remove users from the database
DELETE = 123 
# Gives permission to use general admin cmds
ADMIN = 123 
