[DISCORD]

TOKEN = TODO
GUILDID = TODO

[DATABASE]

DATABASE_USERNAME = TODO
DATABASE_PASSWORD = TODO
DATABASE_HOST = TODO
DATABASE_PORT = TODO
DATABASE_NAME = TODO

[SETTINGS]

BOTNAME = TODO
WHITELIST_LINK = TODO
PERMISSIONS = perm1, perm2, perm3

#Format the entries like the example down below possible perms are, if you want to add additional perms use the PERMISSIONS section above:
#    "startvote",
#    "changemap",
#    "pause",
#    "cheat",
#    "private",
#    "balance",
#    "chat",
#    "kick",
#    "ban",
#    "config",
#    "cameraman",
#    "immune",
#    "manageserver",
#    "featuretest",
#    "reserve",
#    "demos",
#    "clientdemos",
#    "debug",
#    "teamchange",
#    "forceteamchange",
#    "canseeadminchat"
# Seperate perms by |
[PERMISSION_ROLES]
ADMIN = discord_role_id, kick|ban


#Each key in WHITELIST_ROLES should also have an entry in WHITELIST_NAMES and vice versa
[WHITELIST_ROLES]
#The ID's of each role
WHITELIST =  1234

[WHITELIST_NAMES]
#The name in the database of each role
WHITELIST = whitelist

[WHITELIST_ALLOWANCE]
#The number of whitelists each user is allowed to have
WHITELIST = 1

[DISCORD_COMMAND_PERMISSIONS]
# Gives permission to setup the explainer embed
EXPLAIN_EMBED = 123 
# Gives permission to remove users from the database
DELETE = 123 
# Gives permission to use general admin cmds
ADMIN = 123 

